#!/bin/bash

command_run() {
  if [[ ! -d node_modules ]]; then
    npm ci
  fi
  npm test
  npx tsc
  klotho dist --strict --app "$KLOTHO_APP_NAME" --outDir "$klotho_out_dir"
  npm --prefix "$klotho_out_dir" install
}

command_help() {
  echo "Builds and Klotho-compiles the app"
}

